In [18]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler
df = pd.read_csv(r"C:\Users\SCA_11\Downloads\sales_data.csv",encoding="utf-8")
print(df)

       order_id        date region     product  quantity  unit_price  revenue
0          1000  2024-01-01  South      Laptop         1     1170.68  1170.68
1          1000  2024-01-01  South       Mouse         3       25.41    76.23
2          1001  2024-01-01  South       Mouse         4       24.59    98.36
3          1002  2024-01-01  South      Tablet         4      455.91  1823.64
4          1003  2024-01-01  North  Headphones         1       81.23    81.23
...         ...         ...    ...         ...       ...         ...      ...
18054      9976  2024-12-30   East  Smartphone         3      865.41  2596.23
18055      9976  2024-12-30   East       Mouse         3       23.31    69.93
18056      9976  2024-12-30   East        Desk         1      203.90   203.90
18057      9977  2024-12-30   West      Laptop         3     1050.87  3152.61
18058      9978  2024-12-30   West    Keyboard         1       43.82    43.82

[18059 rows x 7 columns]

In [19]:
df.head()

   order_id        date region     product  quantity  unit_price  revenue
0      1000  2024-01-01  South      Laptop         1     1170.68  1170.68
1      1000  2024-01-01  South       Mouse         3       25.41    76.23
2      1001  2024-01-01  South       Mouse         4       24.59    98.36
3      1002  2024-01-01  South      Tablet         4      455.91  1823.64
4      1003  2024-01-01  North  Headphones         1       81.23    81.23

In [21]:
df.tail()

       order_id        date region     product  quantity  unit_price  revenue
18054      9976  2024-12-30   East  Smartphone         3      865.41  2596.23
18055      9976  2024-12-30   East       Mouse         3       23.31    69.93
18056      9976  2024-12-30   East        Desk         1      203.90   203.90
18057      9977  2024-12-30   West      Laptop         3     1050.87  3152.61
18058      9978  2024-12-30   West    Keyboard         1       43.82    43.82

In [20]:
print("\nMissing values before handling")
print(df.isnull().sum())

Missing values before handling
order_id      0
date          0
region        0
product       0
quantity      0
unit_price    0
revenue       0
dtype: int64

In [24]:
print(df.dtypes)

order_id        int64
date           object
region         object
product        object
quantity        int64
unit_price    float64
revenue       float64
dtype: object

In [25]:
df['order_id'] = df['order_id'].astype(float)

In [27]:
print("\nAfter datatype conversion")
print(df.dtypes)

After datatype conversion
order_id      float64
date           object
region         object
product        object
quantity        int64
unit_price    float64
revenue       float64
dtype: object

In [28]:
scaler=StandardScaler()
df[['order_id','unit_price','revenue']]=scaler.fit_transform(df[['order_id','unit_price','revenue']])
print("\ndataset after standardization")

dataset after standardization

In [29]:
df.head()

   order_id        date region     product  quantity  unit_price   revenue
0 -1.729793  2024-01-01  South      Laptop         1    2.459740  0.354382
1 -1.729793  2024-01-01  South       Mouse         3   -0.877638 -0.736819
2 -1.729405  2024-01-01  South       Mouse         4   -0.880027 -0.714755
3 -1.729017  2024-01-01  South      Tablet         4    0.376862  1.005403
4 -1.728630  2024-01-01  North  Headphones         1   -0.714975 -0.731834